# Generated by Django 4.2.30 on 2026-05-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('servant', 'Servant'), ('driver', 'Driver'), ('cook', 'Cook'), ('marketer', 'Marketer'), ('gardener', 'Gardener'), ('security', 'Security')], max_length=50)),
                ('custom_role', models.CharField(blank=True, help_text='Custom role if not in list', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_date', models.IntegerField(help_text='Day of month (1-31)')),
                ('deduction_type', models.CharField(choices=[('per_day_rate', 'Per Day Rate (Salary ÷ 30)'), ('fixed_amount', 'Fixed Amount per Leave')], default='per_day_rate', max_length=20)),
                ('deduction_value', models.DecimalField(blank=True, decimal_places=2, help_text='Per-day deduction amount if fixed', max_digits=10, null=True)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
