# Generated by Django 4.2.30 on 2026-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='deduction_type',
            field=models.CharField(choices=[('per_day_rate', 'Per Day Rate (Salary ÷ actual days)'), ('fixed_amount', 'Fixed Amount per Leave')], default='per_day_rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary_date',
            field=models.IntegerField(choices=[(0, 'Month End'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=1, help_text='0 = Month End, 1-31 = specific day'),
        ),
    ]
