# Generated by Django 4.2.30 on 2026-05-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_salaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('crockery', 'Crockery'), ('equipment', 'Equipment'), ('appliance', 'Appliance'), ('other', 'Other')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_repair', 'Needs Repair'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('dish_name', models.CharField(max_length=200)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('cook', models.ForeignKey(limit_choices_to={'role': 'cook'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('quantity_at_home', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_to_buy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_purchased', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.category')),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.grocerylist')),
            ],
        ),
    ]
